"""Generate eval/score.py from an EvalProfile — templated Python wrapping discovered tools."""

from __future__ import annotations

import shlex
from pathlib import Path

from factory.models import EvalDimension, EvalProfile


_HEADER = '''\
#!/usr/bin/env python3
"""Auto-generated eval script for the Software Factory.

This script was generated by `factory discover`. It runs each eval dimension
as a subprocess and outputs JSON to stdout.

Output format:
    {"results": [{"name": str, "score": float, "weight": float, "passed": bool, "details": str}, ...]}

You can edit this file to add custom evals or adjust weights.
Once edited, it becomes a Tier 1 (explicit) eval — the factory will use it as-is.
"""

import json
import subprocess
import sys

'''


def _generate_eval_function(dim: EvalDimension) -> str:
    """Generate a Python function for one eval dimension."""
    fn_name = f"eval_{dim.name}"
    parts = shlex.split(dim.command)
    cmd_list = repr(parts)

    return f'''\
def {fn_name}() -> dict:
    """{dim.description}"""
    try:
        result = subprocess.run(
            {cmd_list},
            capture_output=True,
            text=True,
            timeout=120,
        )
        passed = result.returncode == 0
        if passed:
            score = 1.0
        else:
            # Partial score: count output lines as a rough error metric
            error_lines = [ln for ln in (result.stdout + result.stderr).splitlines() if ln.strip()]
            if not error_lines:
                score = 0.0
            else:
                score = max(0.0, 1.0 - len(error_lines) * 0.05)
        return {{
            "name": {dim.name!r},
            "score": score,
            "weight": {dim.weight},
            "passed": passed,
            "details": (result.stdout or result.stderr).strip()[-500:],
        }}
    except subprocess.TimeoutExpired:
        return {{
            "name": {dim.name!r},
            "score": 0.0,
            "weight": {dim.weight},
            "passed": False,
            "details": "Timed out after 120s",
        }}

'''


_FOOTER_TEMPLATE = '''\
# Register all eval functions here.
EVALS = [{eval_list}]


def main() -> None:
    results = [fn() for fn in EVALS]
    output = {{"results": results}}
    json.dump(output, sys.stdout, indent=2)
    print()  # trailing newline


if __name__ == "__main__":
    main()
'''


def generate_eval_script(profile: EvalProfile) -> str:
    """Generate the full eval/score.py content from an EvalProfile."""
    parts = [_HEADER]

    for dim in profile.dimensions:
        parts.append(_generate_eval_function(dim))

    fn_names = [f"eval_{dim.name}" for dim in profile.dimensions]
    eval_list = ", ".join(fn_names)
    parts.append(_FOOTER_TEMPLATE.format(eval_list=eval_list))

    return "".join(parts)


def write_eval_script(profile: EvalProfile, project_path: Path) -> Path:
    """Generate and write eval/score.py to the project directory."""
    eval_dir = project_path / "eval"
    eval_dir.mkdir(exist_ok=True)
    script_path = eval_dir / "score.py"
    script_path.write_text(generate_eval_script(profile))
    return script_path
